name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉Wanslu Shop iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      
      - run: flutter pub get
      
      - run: pod repo update
        working-directory: ios

      # Set the bundle identifier
      - name: Update Bundle Identifier
        run: |
          /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier com.k3studio.wanslu" ios/Runner/Info.plist

      - run: flutter build ios --release --no-codesign

      # Ensure the Provisioning Profiles directory exists
      - name: Ensure Provisioning Profiles Directory Exists
        run: mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles

      # Decode and install the provisioning profile
      - name: Decode Provisioning Profile
        run: echo "${{ secrets.PROVISIONING_PROFILE }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/Wanslu.mobileprovision

      # Ensure the certificate directory exists
      - name: Ensure Certificate Directory Exists
        run: mkdir -p ~/certificates

      # Decode and install the P12 certificate
      - name: Decode P12 Certificate
        run: echo "${{ secrets.CERTIFICATE_P12 }}" | base64 --decode > ~/certificates/Wanslu.p12

      # Keychain unlock
      - name: Unlock Keychain
        run: |
          security unlock-keychain -p "${{ secrets.CERTIFICATE_PASSWORD }}" ~/Library/Keychains/login.keychain-db
          security set-key-partition-list -S apple-tool:,apple: -s -k "${{ secrets.CERTIFICATE_PASSWORD }}" ~/Library/Keychains/login.keychain-db

      # Import the certificate to the keychain
      - name: Import P12 Certificate
        run: |
          security import ~/certificates/Wanslu.p12 -P "${{ secrets.CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign -T /usr/bin/security

      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is the first release"
